### ISSUE TITLE
Changing routes renders oldRouteComponent and newRouteComponent together

### ISSUE THREAD

**Issue by julienvincent** [jmurzy/react-router-native#34]
| Dependency | Version |
| --- | --- |
| react-router-native | 2.0.0-alpha.2 |
| react-router | 3.0.0-alpha.1 |
| react-native | 0.30.0 |

When changing routes and no animation is set, both the transitionFrom component and the transitionTo component are briefly rendered together.

This results in a UI that looks something like this:

Device:
###### 

| -- transitionFromComponent --     |
|                                                          |
|                                                          |
|                                                          |
|                                                          |
|                                                          |
|                                                          |
++++++++++++++++++++++++++
| -- transitionToComponent --         |
|                                                          |
|                                                          |
|                                                          |
|                                                          |
|                                                          |
|                                                          |
######

**Comment by jmurzy** [comment]
Thanks for reporting. This is fixed in https://github.com/jmurzy/react-router-native/commit/73cf352326651ff710164020b1186e5c8abe3aa4. Will push a new release shortly. Previously I had to slightly defer execution of the transition animations due to [this bug](https://github.com/facebook/react-native/pull/8709/commits/9af57a79d31b4fb7ceb20587cd85a6ca6a1146dc) in NavigationExperimental. 

🍺
