### ISSUE TITLE
Make compatible with RN 0.32

### ISSUE THREAD

**Issue by jonathanglasmeyer** [jmurzy/react-router-native#36]
React Native 0.32 changes the behaviour of NavigationHeader: it's not positioned absolutely anymore. We need to change the layout of `styles.wrapper`, similar to how its done in this [UIExplorer example diff](https://github.com/facebook/react-native/commit/38979f9c68bd054aca3c6102635b2005914506b1) (just needs `flexDirection: 'column-reverse'`).

This will break layout compatibility with RN < 0.32. Also existing layouts need to remove their padding/margin on their "Page" components which was used to pull them below the Header.

**Comment by jmurzy** [comment]
I have refactored quite a few things that also included support for **v0.32** and onwards but didn't want to push a patch because we are blocked by [this](https://github.com/mjackson/history/commit/27a09b97a248847f504c6e5294fd2ed4093dc861#commitcomment-18617238). 

In the meanwhile, #37 is a great patch. Thanks, Jonathan. 🚀 

🍺

**Comment by jonathanglasmeyer** [comment]
Woa these babel configs in package.json files are a PITA. I was thinking of handling this via a postinstall script that'd remove the entries from the offending package jsons.
