### ISSUE TITLE
Integration with Redux w/ HMR

### ISSUE THREAD

**Issue by deoqc** [jmurzy/react-router-native#47]
Is integration with redux, in a sense of [react-router-redux](https://github.com/reactjs/react-router-redux), on then table?

I'm currently using Navigator but the lack of HMR really slows down development.

**Comment by jmurzy** [comment]
Does [this](https://github.com/jmurzy/react-router-native/tree/master/docs#redux-support) setup not work? I was hoping we would support it out of the box. But haven't given it a try to be quite honest. We need a simple Redux example in the repo. If you want to take a stab at it, please send a PR over. Otherwise, I will get to it soon. 

🍺

**Comment by deoqc** [comment]
Sorry for missing it. I will _probably_ only try-out react-router-native when v4 is out, so I probably won't be able to help soon enough.

Thanks for this great work.
